set nowrap
set linebreak
set foldmethod=indent
set foldnestmax=3
set nofoldenable
set backspace=indent,eol,start
set autoindent
set smartindent
set shiftwidth=2
set softtabstop=2
set tabstop=2
set expandtab
set showmatch
set ignorecase
set smartcase
set smarttab
set hlsearch
set incsearch
set undolevels=1000
set title
set visualbell
syntax enable
set t_Co=256
nnoremap ; :
colorscheme flattened_dark
set number
set showcmd
set showmode
set noswapfile
set nobackup
set nowb

exec pathogen#infect()
call pathogen#runtime_append_all_bundles()
call pathogen#helptags()
